package ui_swing;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import run_main.Main;
import sql_actions.Delete;
import sql_actions.Read;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author gaabr
 */
public class Tela_principal_adm extends javax.swing.JPanel {

    /**
     * Creates new form Tela_adm
     */
    public Tela_principal_adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        mesaOpcoes = new javax.swing.JTabbedPane();
        Painel_BotaoAdd = new javax.swing.JPanel();
        BotaoAdd = new javax.swing.JButton();
        painel_RemoverFilmes = new javax.swing.JPanel();
        TextoID = new javax.swing.JLabel();
        IDdofilmeAqui = new javax.swing.JTextField();
        botaoConfirmaExcluir = new javax.swing.JButton();
        Painel_ListarFilmes = new javax.swing.JPanel();
        PaineldasListas = new javax.swing.JPanel();
        botaoUsuarios = new javax.swing.JButton();
        BotaoListarPedido = new javax.swing.JButton();
        BotaoListaFilmes = new javax.swing.JButton();
        Botaosecoes = new javax.swing.JButton();
        textoNakafilms = new javax.swing.JLabel();
        IDdasessaoaqui = new JTextField();
        botaoConfirmaExcluirsessao = new JButton();
        TextoIDsessao = new JLabel();

        setBackground(new java.awt.Color(13, 30, 64));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setLayout(null);

        PaineldasListas.setLayout(new java.awt.BorderLayout());
        Footer = Metodos_swing.footer();
        add(Footer);
        Footer.setBounds(0, 700, 1366, 50);

        mesaOpcoes.setBackground(new java.awt.Color(242, 240, 201));

        Painel_BotaoAdd.setBackground(new java.awt.Color(242, 240, 201));

        BotaoAdd.setText("ADICIONAR FILME");
        BotaoAdd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.getCardLayout().show(Main.getCards(), "cad_filme");
            }
        });
        javax.swing.GroupLayout Painel_BotaoAddLayout = new javax.swing.GroupLayout(Painel_BotaoAdd);
        Painel_BotaoAdd.setLayout(Painel_BotaoAddLayout);
        Painel_BotaoAddLayout.setHorizontalGroup(
                Painel_BotaoAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Painel_BotaoAddLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(BotaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(214, Short.MAX_VALUE))
        );
        Painel_BotaoAddLayout.setVerticalGroup(
                Painel_BotaoAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Painel_BotaoAddLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(BotaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(124, Short.MAX_VALUE))
        );

        mesaOpcoes.addTab("ADICIONAR FILME", Painel_BotaoAdd);

        painel_RemoverFilmes.setBackground(new java.awt.Color(242, 240, 201));
        painel_RemoverFilmes.setLayout(null);

        TextoID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoID.setText("ID do filme:");
        painel_RemoverFilmes.add(TextoID);
        TextoID.setBounds(58, 170, 220, 32);

        painel_RemoverFilmes.add(IDdofilmeAqui);
        IDdofilmeAqui.setBounds(260, 170, 150, 32);

        botaoConfirmaExcluir.setText("Confirmar");
        botaoConfirmaExcluir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int id = Integer.parseInt(getIDdofilmeAqui().getText());
                try {
                    Delete.filme(id);
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
        painel_RemoverFilmes.add(botaoConfirmaExcluir);
        botaoConfirmaExcluir.setBounds(460, 170, 150, 23);

        TextoIDsessao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoIDsessao.setText("ID da sessão:");
        painel_RemoverFilmes.add(TextoIDsessao);
        TextoIDsessao.setBounds(58, 221, 220, 32);

        painel_RemoverFilmes.add(IDdasessaoaqui);
        IDdasessaoaqui.setBounds(260, 221, 152, 32);

        botaoConfirmaExcluirsessao.setText("Confirmar");
        botaoConfirmaExcluirsessao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int id = Integer.parseInt(getIDdasessaoaqui().getText());
                try {
                    Delete.sessao(id);
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
        painel_RemoverFilmes.add(botaoConfirmaExcluirsessao);
        botaoConfirmaExcluirsessao.setBounds(460, 221, 150, 23);
        mesaOpcoes.addTab("REMOVER FILME", painel_RemoverFilmes);

        Painel_ListarFilmes.setBackground(new java.awt.Color(242, 240, 201));
        Painel_ListarFilmes.setLayout(null);

        Painel_ListarFilmes.add(PaineldasListas);
        PaineldasListas.setBounds(123, 56, 628, 315);

        botaoUsuarios.setText("Lista Usuarios");
        botaoUsuarios.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Read.getUsuario();
            }
        });
        Painel_ListarFilmes.add(botaoUsuarios);
        botaoUsuarios.setBounds(630, 410, 190, 23);

        BotaoListarPedido.setText("Listar Pedidos");
        BotaoListarPedido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Read.getPedidos();
            }
        });
        Painel_ListarFilmes.add(BotaoListarPedido);
        BotaoListarPedido.setBounds(20, 410, 200, 23);

        BotaoListaFilmes.setText("Listar Filmes");
        BotaoListaFilmes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Read.getFilmes();
            }
        });
        Painel_ListarFilmes.add(BotaoListaFilmes);
        BotaoListaFilmes.setBounds(230, 410, 200, 23);

        Botaosecoes.setText("Listar sessões");
        Botaosecoes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Read.getSessao();
            }
        });
        Painel_ListarFilmes.add(Botaosecoes);
        Botaosecoes.setBounds(440, 410, 180, 23);

        mesaOpcoes.addTab("LISTAR", Painel_ListarFilmes);

        add(mesaOpcoes);
        mesaOpcoes.setBounds(300, 120, 830, 520);

        textoNakafilms.setBackground(new java.awt.Color(242, 27, 127));
        textoNakafilms.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        textoNakafilms.setForeground(new java.awt.Color(242, 27, 127));
        textoNakafilms.setText("Nakafilms adm");
        add(textoNakafilms);
        textoNakafilms.setBounds(300, 20, 550, 70);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton BotaoAdd;
    private javax.swing.JButton BotaoListaFilmes;
    private javax.swing.JButton BotaoListarPedido;
    private javax.swing.JButton Botaosecoes;
    private javax.swing.JPanel Footer;
    private static javax.swing.JTextField IDdofilmeAqui;
    private static javax.swing.JTextField IDdasessaoaqui;
    private javax.swing.JPanel Painel_BotaoAdd;
    private static javax.swing.JPanel Painel_ListarFilmes;
    private static javax.swing.JPanel PaineldasListas;
    private javax.swing.JLabel TextoID;
    private javax.swing.JLabel TextoIDsessao;
    private javax.swing.JButton botaoConfirmaExcluir;
    private javax.swing.JButton botaoConfirmaExcluirsessao;
    private javax.swing.JButton botaoUsuarios;
    private javax.swing.JTabbedPane mesaOpcoes;
    private javax.swing.JPanel painel_RemoverFilmes;
    private javax.swing.JLabel textoNakafilms;
    // End of variables declaration


    public static JTextField getIDdasessaoaqui() {
        return IDdasessaoaqui;
    }

    public static JTextField getIDdofilmeAqui() {
        return IDdofilmeAqui;
    }

    public static JPanel getPaineldasListas() {
        return PaineldasListas;
    }

    public static JPanel getPainel_ListarFilmes() {
        return Painel_ListarFilmes;
    }
}
